# Generated by Django 3.1.3 on 2021-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdminRole',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('role_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Bot Admin Role',
                'verbose_name_plural': 'Bot Admin Roles',
                'default_permissions': (),
            },
        ),
    ]
